---
- name: Download Helm 3
  get_url:
    url: "{{ helm_url }}"
    dest: /tmp/get_helm.sh
    mode: 0775
  register: download

- name: Install Helm
  shell:
    /tmp/get_helm.sh
  when:
    - download.failed|bool == false
  register: install_helm

- name:
  debug: var=install_helm

